### PR TITLE
Add click_govuk_button helper

### PR DESCRIPTION
**Pull request by frankieroberto**
Following the `click_govuk_link` helper added in #6, this does the same but for buttons.

It will work with both actual `<button>`s, and with links styled as buttons – on the basis that the tests should reflect how the interfaces appears to users, rather than the underlying implementation.

The helper currently does these checks:

* full text of the button is specified, including any visually-hidden text
* the button text is unique within the page
* the `gov-button` class is added
* `data-module="govuk-button"` is added (this is used by javascript which adds some accessibility enhancements)
* if it’s a link styled as a button, then `role="button"` is present

### CODE REVIEW

**Comment by frankieroberto** [comment]
@paulrobertlloyd @joelanman @peteryates following on from `click_govuk_link`, here’s `click_govuk_button`...

I've done the basic checks I could think of, but there might be some more:

* only a single "primary" green button (is this enough of a rule to be strictly enforced?)
* `draggable="false"` is added to any links styled as buttons (or is this only for the start button?)
* check button isn’t disabled – this is strongly discouraged but maybe it's worth enforcing, or at least making people explicitly opt-in to it by using `click_govuk_button('Continue', disabled: true)` or something?
* `data-prevent-double-click="true"` – I’m not sure we should check this for now, as the guidance suggests using server-side fixes for this instead if possible?

Anything else?

**Comment by frankieroberto** [comment]
Ok, I decided to add checks for:

* `draggable="false"` - on any links styled as buttons
* that the button isn’t disabled unless you explicitly opt-in by using `click_govuk_button("Text", disabled: true)`, in which case it checks that both the css class and the aria attribute are also added

Decided against checking there’s only one primary button, and that `data-prevent-double-click="true"` is added, for now - as neither of those are hard rules.

**Comment by joelanman** [comment]
is there a 'warning' level for only one primary button?

**Comment by frankieroberto** [comment]
> is there a 'warning' level for only one primary button?

Hmm, interesting idea! I don't think the rspec framework itself has a "warning" level, as tests have to either pass or fail?

Potentially we could output warning messages to the console log, unless you deliberately silence them. But they might still get ignored.

Another option would be to make the test fail unless you explicitly override it somehow. I did that for the disabled links, where you have to pass `disabled: true`. Could do something similar:

```ruby
  click_govuk_button("Continue", ignore_other_primary_buttons: true)
```

..or some kind of global setting somewhere.  Feels a bit icky though, somehow?

Another alternative would be just to make the helper more opinionated and always fail if there are 2 primary buttons.  Teams could still fall back to using `click_button` if they really wanted to ignore the warning...

I can't decide yet!

**Comment by paulrobertlloyd** [comment]
Reading this and can’t help but wonder if it’s possible you could go too far with this helper. Some things, especially the more nuanced they get, should probably be left to individual teams to decide (and and then add tests against if desired).

Is 2 green primary buttons on a page wrong? Who knows, context is everything. A helper enforcing hard and fast rules without having that context seems like a dangerous path to follow.

**Comment by frankieroberto** [comment]
@paulrobertlloyd I'm inclined to agree - at least for now.  I’ve added a separate issue to consider adding this in future: #16

I think the approach for disabled buttons is ok, as that guidance is a bit stronger (even if it still says "avoid if possible").

It’s quite unlikely that you'd write a test to click on a disabled button (although you could, to check nothing happens), so checking that the button isn't disabled feels like a valuable default. This also [matches the default behaviour](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/spec/session/click_link_or_button_spec.rb#L103-L108) of Capybara's `click_button` helper:

**Comment by frankieroberto** [comment]
I've also spun out the question of supporting `data-prevent-double-click="true"` into a separate issue for future discussion: #17

**Comment by joelanman** [comment]
I would err on the side of the single green error:

>Avoid using multiple default buttons on a single page. Having more than one main call to action reduces their impact, and makes it harder for users to know what to do next.

The option to manually ignore with a flag sounds good, that means you know about the issue and made a conscious decision

**Pull request merged**
