### PR TITLE
Add helper: click_govuk_link

### PR DESCRIPTION
**Pull request by frankieroberto**
This is a drop-in replacement for the capybara `click_link` helper, but also checks that:

* there aren’t 2 or more links with the same link text
* the link has the `govuk-link` class (or another link class from the GOV.UK Design System)
* the link text isn't ambiguous like "Change"
* the full link text is specified (including any visually-hidden text) rather than a partial match

### CODE REVIEW

**Comment by frankieroberto** [comment]
@paulrobertlloyd @peteryates @joelanman can you think of any other link-related accessibility or usability checks that could be included?

**Comment by joelanman** [comment]
- I think they can have same link text if same href
 - if it has govuk-button class, that it also has the right role and data attributes
 - maybe a warning if the `_target` is `blank`?

**Comment by paulrobertlloyd** [comment]
Building on @joelanman’s suggestion, how about a warning if the target is `_blank` but the link text doesn't contain the words ‘new tab’?

**Comment by frankieroberto** [comment]
> * I think they can have same link text if same href

Oh, I wasn’t sure that was allowed. Will check.

> * if it has govuk-button class, that it also has the right role and data attributes

I was planning on adding a separate `click_govuk_button` helper which would handle both real buttons and links styles as buttons. But I think it’s a good idea to detect them within `click_govuk_link` and raise an error suggesting people switch to the other helper. 👍

> * maybe a warning if the `_target` is `blank`?

👍

> * that it doesnt have a `button` inside it

@joelanman could you explain this one? I’ve never seen a button within a link… 🤔

**Comment by joelanman** [comment]
ha there's no explanation - some people do it!

**Comment by paulrobertlloyd** [comment]
> You can see the documentation page for this helper here: https://x-govuk.github.io/govuk-rspec-helpers/click-govuk-link/

Ooh, documentation. Sounds like somebody wants a homepage illustration, right? Right!?

**Comment by peteryates** [comment]
I like this ❤️ 

One thing that is probably worth checking for is when `target: "_blank"` there's a `rel: "noreferrer noopener"` present too?

Many of these will be solved by [the new link helpers](https://github.com/x-govuk/govuk-components/pull/419) coming in GOV.UK Components v5.

**Comment by frankieroberto** [comment]
@peteryates good shout! I've added that as an issue here: #14 - will open a PR shortly.

**Pull request merged**
